In [2]:
import pandas as pd

In [3]:
df_crm_cust = pd.read_csv('../datasets/source_crm/cust_info.csv')
df_crm_prd = pd.read_csv('../datasets/source_crm/prd_info.csv')
df_crm_sales = pd.read_csv('../datasets/source_crm/sales_details.csv')
df_erp_cust = pd.read_csv('../datasets/source_erp/CUST_AZ12.csv')
df_erp_loc = pd.read_csv('../datasets/source_erp/LOC_A101.csv')
df_erp_px_cat = pd.read_csv('../datasets/source_erp/PX_CAT_G1V2.csv')

In [ ]:
df_crm_cust.head()

,cst_id,cst_key,cst_firstname,cst_lastname,cst_marital_status,cst_gndr,cst_create_date
0,11000.0,AW00011000,Jon,Yang,M,M,2025-10-06
1,11001.0,AW00011001,Eugene,Huang,S,M,2025-10-06
2,11002.0,AW00011002,Ruben,Torres,M,M,2025-10-06
3,11003.0,AW00011003,Christy,Zhu,S,F,2025-10-06
4,11004.0,AW00011004,Elizabeth,Johnson,S,F,2025-10-06

In [ ]:
df_crm_cust.head()

,cst_id,cst_key,cst_firstname,cst_lastname,cst_marital_status,cst_gndr,cst_create_date
0,11000.0,AW00011000,Jon,Yang,M,M,2025-10-06
1,11001.0,AW00011001,Eugene,Huang,S,M,2025-10-06
2,11002.0,AW00011002,Ruben,Torres,M,M,2025-10-06
3,11003.0,AW00011003,Christy,Zhu,S,F,2025-10-06
4,11004.0,AW00011004,Elizabeth,Johnson,S,F,2025-10-06

In [4]:
df_crm_prd.head(20)

,prd_id,prd_key,prd_nm,prd_cost,prd_line,prd_start_dt,prd_end_dt
0,210,CO-RF-FR-R92B-58,HL Road Frame - Black- 58,NaN,R,2003-07-01,NaN
1,211,CO-RF-FR-R92R-58,HL Road Frame - Red- 58,NaN,R,2003-07-01,NaN
2,212,AC-HE-HL-U509-R,Sport-100 Helmet- Red,12.0,S,2011-07-01,2007-12-28
3,213,AC-HE-HL-U509-R,Sport-100 Helmet- Red,14.0,S,2012-07-01,2008-12-27
4,214,AC-HE-HL-U509-R,Sport-100 Helmet- Red,13.0,S,2013-07-01,NaN
5,215,AC-HE-HL-U509,Sport-100 Helmet- Black,12.0,S,2011-07-01,2007-12-28
6,216,AC-HE-HL-U509,Sport-100 Helmet- Black,14.0,S,2012-07-01,2008-12-27
7,217,AC-HE-HL-U509,Sport-100 Helmet- Black,13.0,S,2013-07-01,NaN
8,218,CL-SO-SO-B909-M,Mountain Bike Socks- M,3.0,M,2011-07-01,2007-12-28
9,219,CL-SO-SO-B909-L,Mountain Bike Socks- L,3.0,M,2011-07-01,2007-12-28
10,220,AC-HE-HL-U509-B,Sport-100 Helmet- Blue,12.0,S,2011-07-01,2007-12-28
11,221,AC-HE-HL-U509-B,Sport-100 Helmet- Blue,14.0,S,2012-07-01,2008-12-27
12,222,AC-HE-HL-U509-B,Sport-100 Helmet- Blue,13.0,S,2013-07-01,NaN
13,223,CL-CA-CA-1098,AWC Logo Cap,6.0,S,2011-07-01,2007-12-28
14,224,CL-CA-CA-1098,AWC Logo Cap,5.0,S,2012-07-01,2008-12-27
15,225,CL-CA-CA-1098,AWC Logo Cap,7.0,S,2013-07-01,NaN
16,226,CL-JE-LJ-0192-S,Long-Sleeve Logo Jersey- S,32.0,S,2011-07-01,2007-12-28
17,227,CL-JE-LJ-0192-S,Long-Sleeve Logo Jersey- S,29.0,S,2012-07-01,2008-12-27
18,228,CL-JE-LJ-0192-S,Long-Sleeve Logo Jersey- S,38.0,S,2013-07-01,NaN
19,229,CL-JE-LJ-0192-M,Long-Sleeve Logo Jersey- M,32.0,S,2011-07-01,2007-12-28

In [11]:
df_crm_sales.head()

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price
0,SO43697,BK-R93R-62,21768,20101229,20110105,20110110,3578.0,1,3578.0
1,SO43698,BK-M82S-44,28389,20101229,20110105,20110110,3400.0,1,3400.0
2,SO43699,BK-M82S-44,25863,20101229,20110105,20110110,3400.0,1,3400.0
3,SO43700,BK-R50B-62,14501,20101229,20110105,20110110,699.0,1,699.0
4,SO43701,BK-M82S-44,11003,20101229,20110105,20110110,3400.0,1,3400.0

In [10]:
df_erp_cust.head()

             CID       BDATE     GEN
0  NASAW00011000  1971-10-06    Male
1  NASAW00011001  1976-05-10    Male
2  NASAW00011002  1971-02-09    Male
3  NASAW00011003  1973-08-14  Female
4  NASAW00011004  1979-08-05  Female

In [9]:
df_erp_loc.head()

           CID      CNTRY
0  AW-00011000  Australia
1  AW-00011001  Australia
2  AW-00011002  Australia
3  AW-00011003  Australia
4  AW-00011004  Australia

In [8]:
df_erp_px_cat.head()

      ID          CAT             SUBCAT MAINTENANCE
0  AC_BR  Accessories         Bike Racks         Yes
1  AC_BS  Accessories        Bike Stands          No
2  AC_BC  Accessories  Bottles and Cages          No
3  AC_CL  Accessories           Cleaners         Yes
4  AC_FE  Accessories            Fenders          No